### ISSUE TITLE
rtt_pcl fails to build on Kinetic

### ISSUE THREAD

**Issue by tfoote** [orocos/rtt_pcl#2]
From: http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__rtt_pcl__ubuntu_xenial_amd64__binary/118/console

```
00:01:16.080 # BEGIN SUBSECTION: append build timestamp
00:01:16.161 Invoking 'debchange -v 0.1.0-1xenial-20200123-231826+0000 -p -D xenial -u high -m Append timestamp when binarydeb was built.' in '/tmp/binarydeb/ros-kinetic-rtt-pcl-0.1.0'
00:01:16.276 # END SUBSECTION
00:01:18.332 Looking for the '.dsc' file of package 'ros-kinetic-rtt-pcl' with version '0.1.0-1'
00:01:19.298 Traceback (most recent call last):
00:01:19.298   File "/usr/lib/python3/dist-packages/apt/cache.py", line 259, in __getitem__
00:01:19.309     return self._weakref[key]
00:01:19.309   File "/usr/lib/python3.5/weakref.py", line 131, in __getitem__
00:01:19.320     o = self.data[key]()
00:01:19.320 KeyError: 'libpcl1.8-dev'
00:01:19.320 
00:01:19.320 During handling of the above exception, another exception occurred:
00:01:19.320 
00:01:19.320 Traceback (most recent call last):
00:01:19.320   File "/usr/lib/python3/dist-packages/apt/cache.py", line 263, in __getitem__
00:01:19.320     rawpkg = self._cache[key]
00:01:19.320 KeyError: 'libpcl1.8-dev'
00:01:19.320 
00:01:19.320 During handling of the above exception, another exception occurred:
00:01:19.320 
00:01:19.320 Traceback (most recent call last):
00:01:19.320   File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 166, in <module>
00:01:19.320     main()
00:01:19.320   File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 85, in main
00:01:19.320     apt_cache, debian_pkg_names)
00:01:19.320   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 154, in get_binary_package_versions
00:01:19.320     pkg = apt_cache[debian_pkg_name]
00:01:19.320   File "/usr/lib/python3/dist-packages/apt/cache.py", line 265, in __getitem__
00:01:19.320     raise KeyError('The cache has no package named %r' % key)
```

**Comment by meyerj** [comment]
Thanks for the report. Apparently I was using a non-default rosdep config when I released the package (and `rtt_pcl_ros`) with Bloom in September and also did not follow-up anymore. We used to overwrite the pcl keys to point to a custom build of PCL 1.8 in xenial for internal packages.

Fixed in https://github.com/ros/rosdistro/pull/23594.
